#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ContractRouteGroup {
    pub name: &'static str,
    pub routes: &'static [&'static str],
}

pub const PUBLIC_API_ROUTES: &[&str] = &[
    "GET /",
    "GET /v1/models",
    "POST /v1/chat/completions",
    "POST /v1/completions",
    "POST /v1/messages",
    "POST /v1/messages/count_tokens",
    "GET /v1/responses",
    "POST /v1/responses",
    "POST /v1/responses/compact",
    "GET /v1beta/models",
    "GET /v1beta/models/*action",
    "POST /v1beta/models/*action",
    "POST /v1internal:method",
];

pub const OAUTH_CALLBACK_ROUTES: &[&str] = &[
    "GET /anthropic/callback",
    "GET /codex/callback",
    "GET /google/callback",
    "GET /antigravity/callback",
    "GET /keep-alive",
];

pub const MANAGEMENT_ROUTE_GROUPS: &[ContractRouteGroup] = &[
    ContractRouteGroup {
        name: "quota",
        routes: &[
            "GET /v0/management/usage",
            "GET /v0/management/codex/quota-snapshots",
            "POST /v0/management/codex/quota-snapshots/refresh",
        ],
    },
    ContractRouteGroup {
        name: "auth-files",
        routes: &[
            "GET /v0/management/auth-files",
            "GET /v0/management/auth-files/models",
            "GET /v0/management/auth-files/download",
            "POST /v0/management/auth-files",
            "POST /v0/management/gemini-web-token",
            "POST /v0/management/vertex/import",
            "DELETE /v0/management/auth-files",
            "PATCH /v0/management/auth-files/status",
            "PATCH /v0/management/auth-files/fields",
        ],
    },
    ContractRouteGroup {
        name: "oauth-login",
        routes: &[
            "GET /v0/management/anthropic-auth-url",
            "GET /v0/management/codex-auth-url",
            "GET /v0/management/gemini-cli-auth-url",
            "GET /v0/management/antigravity-auth-url",
            "GET /v0/management/kimi-auth-url",
            "GET /v0/management/qwen-auth-url",
            "POST /v0/management/oauth-callback",
            "GET /v0/management/get-auth-status",
        ],
    },
    ContractRouteGroup {
        name: "config-basics",
        routes: &[
            "GET /v0/management/config",
            "GET /v0/management/config.yaml",
            "PUT /v0/management/config.yaml",
            "GET /v0/management/debug",
            "PUT /v0/management/debug",
            "PATCH /v0/management/debug",
            "GET /v0/management/logging-to-file",
            "PUT /v0/management/logging-to-file",
            "PATCH /v0/management/logging-to-file",
            "GET /v0/management/logs-max-total-size-mb",
            "PUT /v0/management/logs-max-total-size-mb",
            "PATCH /v0/management/logs-max-total-size-mb",
            "GET /v0/management/error-logs-max-files",
            "PUT /v0/management/error-logs-max-files",
            "PATCH /v0/management/error-logs-max-files",
            "GET /v0/management/usage-statistics-enabled",
            "PUT /v0/management/usage-statistics-enabled",
            "PATCH /v0/management/usage-statistics-enabled",
            "GET /v0/management/proxy-url",
            "PUT /v0/management/proxy-url",
            "PATCH /v0/management/proxy-url",
            "DELETE /v0/management/proxy-url",
            "GET /v0/management/quota-exceeded/switch-project",
            "PUT /v0/management/quota-exceeded/switch-project",
            "PATCH /v0/management/quota-exceeded/switch-project",
            "GET /v0/management/quota-exceeded/switch-preview-model",
            "PUT /v0/management/quota-exceeded/switch-preview-model",
            "PATCH /v0/management/quota-exceeded/switch-preview-model",
            "GET /v0/management/request-log",
            "PUT /v0/management/request-log",
            "PATCH /v0/management/request-log",
            "GET /v0/management/ws-auth",
            "PUT /v0/management/ws-auth",
            "PATCH /v0/management/ws-auth",
            "GET /v0/management/ampcode/upstream-url",
            "PUT /v0/management/ampcode/upstream-url",
            "PATCH /v0/management/ampcode/upstream-url",
            "DELETE /v0/management/ampcode/upstream-url",
            "GET /v0/management/ampcode/upstream-api-key",
            "PUT /v0/management/ampcode/upstream-api-key",
            "PATCH /v0/management/ampcode/upstream-api-key",
            "DELETE /v0/management/ampcode/upstream-api-key",
            "GET /v0/management/ampcode/restrict-management-to-localhost",
            "PUT /v0/management/ampcode/restrict-management-to-localhost",
            "PATCH /v0/management/ampcode/restrict-management-to-localhost",
            "GET /v0/management/request-retry",
            "PUT /v0/management/request-retry",
            "PATCH /v0/management/request-retry",
            "GET /v0/management/max-retry-interval",
            "PUT /v0/management/max-retry-interval",
            "PATCH /v0/management/max-retry-interval",
            "GET /v0/management/force-model-prefix",
            "PUT /v0/management/force-model-prefix",
            "PATCH /v0/management/force-model-prefix",
            "GET /v0/management/routing/strategy",
            "PUT /v0/management/routing/strategy",
            "PATCH /v0/management/routing/strategy",
        ],
    },
    ContractRouteGroup {
        name: "provider-config",
        routes: &[
            "GET /v0/management/api-keys",
            "PUT /v0/management/api-keys",
            "PATCH /v0/management/api-keys",
            "DELETE /v0/management/api-keys",
            "GET /v0/management/gemini-api-key",
            "PUT /v0/management/gemini-api-key",
            "PATCH /v0/management/gemini-api-key",
            "DELETE /v0/management/gemini-api-key",
            "GET /v0/management/claude-api-key",
            "PUT /v0/management/claude-api-key",
            "PATCH /v0/management/claude-api-key",
            "DELETE /v0/management/claude-api-key",
            "GET /v0/management/codex-api-key",
            "PUT /v0/management/codex-api-key",
            "PATCH /v0/management/codex-api-key",
            "DELETE /v0/management/codex-api-key",
            "GET /v0/management/openai-compatibility",
            "PUT /v0/management/openai-compatibility",
            "PATCH /v0/management/openai-compatibility",
            "DELETE /v0/management/openai-compatibility",
            "GET /v0/management/vertex-api-key",
            "PUT /v0/management/vertex-api-key",
            "PATCH /v0/management/vertex-api-key",
            "DELETE /v0/management/vertex-api-key",
            "GET /v0/management/oauth-excluded-models",
            "PUT /v0/management/oauth-excluded-models",
            "PATCH /v0/management/oauth-excluded-models",
            "DELETE /v0/management/oauth-excluded-models",
            "GET /v0/management/oauth-model-alias",
            "PUT /v0/management/oauth-model-alias",
            "PATCH /v0/management/oauth-model-alias",
            "DELETE /v0/management/oauth-model-alias",
        ],
    },
];
